import type { PropType, TransitionProps } from "vue";
import type { ColorVariant, TextColorVariant, BProgressBarProps } from "bootstrap-vue-next";

export const customAlert = {
    alertClass: { type: [String, Array, Object] as PropType<any>, required: true, default: undefined },
    bgVariant: { type: String as PropType<ColorVariant | null>, required: true, default: null },
    body: { type: String as PropType<string>, default: undefined },
    bodyClass: { type: [String, Array, Object] as PropType<any>, required: true, default: undefined },
    closeClass: { type: [String, Array, Object] as PropType<any>, required: true, default: undefined },
    closeContent: { type: String as PropType<string>, required: true, default: undefined },
    closeLabel: { type: String as PropType<string>, required: true, default: "Close" },
    closeVariant: { type: String as PropType<ColorVariant | null>, required: true, default: null },
    dismissible: { type: Boolean, required: true, default: false },
    headerClass: { type: [String, Array, Object] as PropType<any>, required: true, default: undefined },
    headerTag: { type: String, default: "div" },
    id: { type: String, required: true, default: undefined },
    initialAnimation: { type: Boolean, required: true, default: false },
    interval: { type: [Number, String] as PropType<number | "requestAnimationFrame">, required: true, default: "requestAnimationFrame" },
    isStatus: { type: Boolean, required: true, default: false },
    lazy: { type: Boolean, required: true, default: false },
    modelValue: { type: [Boolean, Number] as PropType<boolean | number>, required: true, default: false },
    noAnimation: { type: Boolean, required: true, default: false },
    noFade: { type: Boolean, required: true, default: false },
    noHoverPause: { type: Boolean, required: true, default: false },
    noResumeOnHoverLeave: { type: Boolean, required: true, default: false },
    progressProps: { type: Object as PropType<Partial<Omit<BProgressBarProps, "label" | "max" | "value">>>, required: true, default: undefined },
    show: { type: Boolean, required: true, default: false },
    showOnPause: { type: Boolean, required: true, default: true },
    textVariant: { type: String as PropType<TextColorVariant | null>, required: true, default: null },
    title: { type: String, required: true },
    transProps: { type: Object as PropType<TransitionProps>, required: true, default: undefined },
    unmountLazy: { type: Boolean, required: true, default: false },
    variant: { type: String as PropType<ColorVariant | null>, required: true, default: null },
    visible: { type: Boolean, required: true, default: false },
};
