import type { PropType } from "vue";

export const customCardProps = {
    id: { type: String as PropType<string>, default: '' },
    title: { type: String as PropType<string>, required: true },
    subTitle: { type: String as PropType<string>, default: '' },
    subTitleTag: { type: String as PropType<string>, default: 'h6' },
    titleTag: { type: String as PropType<string>, default: 'h4' },
    classCard: { type: String as PropType<string>, default: '' },
    imgSrc: { type: String as PropType<string>, required: true },
    imgAlt: { type: String as PropType<string>, required: true},
    imgTop: { type: Boolean as PropType<boolean>, default: false },
    imgBottom: { type: Boolean as PropType<boolean>, default: false },
    imgEnd: { type: Boolean as PropType<boolean>, default: false },
    imgStart: { type: Boolean as PropType<boolean>, default: false },
    imgHeight: { type: [String, Number] as PropType<string | number>, default: 300 },
    imgWidth: { type: [String, Number] as PropType<string | number>, default: '' },
    noBody: { type: Boolean as PropType<boolean>, default: false },
    overlay: { type: Boolean as PropType<boolean>, default: false },
    tag: { type: String as PropType<string>, default: 'div' },
    headerCard: { type: String as PropType<string>, default: '' },
    headerClass: { type: String as PropType<string>, default: '' },
    footerCard: { type: String as PropType<string>, default: '' },
    footerClass: { type: String as PropType<string>, default: '' },
    descriptionCard: { type: String as PropType<string>, default: '' },
    customClassText: { type: String as PropType<string>, default: '' },
    customCardLink: { type: String as PropType<string>, default: '' },
    titleCustomLink: { type: String as PropType<string>, default: '' },
    showBtn: { type: Boolean as PropType<boolean>, default: false },
    idBtn: { type: String as PropType<string>, default: '' },
    linkBtn: { type: String as PropType<string>, required: true },
    labelBtn: { type: String as PropType<string>, required: true },
    btnClass: { type: String as PropType<string>, default: '' },
    variantBtn: { type: String as PropType<string>, default: '' },
    typeButton: { type: String as PropType<string>, default: 'button', validator: (value: string) => ['button', 'submit', 'reset'].includes(value) },
    enableHoverAnimation: { type: Boolean as PropType<boolean>, default: false },
    hoverBorderColor: { type: String as PropType<string>, default: '#4a9eff' },
    hoverBorderWidth: { type: String as PropType<string>, default: '2px' },
    hoverTransitionDuration: { type: String as PropType<string>, default: '0.3s' }
};
