import type { PropType } from "vue";

export const customInput = {
    id: { type: String as PropType<string>, required: true },
    title: { type: String as PropType<string>, required: true },
    searchable: { type: Boolean as PropType<boolean>, default: false },
    placeholder: { type: String as PropType<string>, required: false, default: '' },
    inputType: { type: String as PropType<string>, default: 'text' },
    autocomplete: { type: String as PropType<string>, default: 'on' },
    maxlength: { type: Number as PropType<number>, default: null },
    inputClass: { type: String as PropType<string>, default: '' },
    labelClass: { type: String as PropType<string>, default: '' },
    customClass: { type: String as PropType<string>, default: '' },
    numeric: { type: Boolean as PropType<boolean>, default: false },
    integer: { type: Boolean as PropType<boolean>, default: false },
    decimal: { type: Boolean as PropType<boolean>, default: false },
    required: { type: Boolean as PropType<boolean>, default: false },
    requiredIf: { type: Boolean as PropType<boolean>, default: false },
    minLength: { type: [Number, String] as PropType<number | string>, default: 0 },
    canShowPassword: { type: Boolean as PropType<boolean>, default: true },
    toolTip: { type: String as PropType<string>, default: '' },
    textArea: { type: Boolean as PropType<boolean>, default: false },
    disabled: { type: Boolean as PropType<boolean>, default: false },
    rowTextArea: { type: Number as PropType<number>, default: 0 },
    titleToolTip: { type: String as PropType<string>, default: '' },
    customValidationTitle: { type: String as PropType<string>, default: '' },
    betweenValue: { type: Array as PropType<number[]>, default: () => [] },
    listSearch: { type: Array as PropType<number[]>, default: () => [] },
    regex: { type: RegExp as PropType<RegExp>, default: undefined },
    maximumFractalDigits: { type: Number as PropType<number>, default: undefined },
    keyupEvent: { type: Function as PropType<(payload?: KeyboardEvent) => void>, default: () => {} },
    inputEvent: { type: Function as PropType<(payload?: Event) => void>, default: () => {} },
    focusoutTextArea: { type: Function as PropType<(payload?: FocusEvent) => void>, default: () => {} },
    errorMandatory: {type: String as PropType<string>, default: 'value mandatory'}
}
