import type { PropType } from "vue";

export type dropdownItem = {
    value: string,
    name: string,
    link: string
}

export const CustomDropdown = {
    dropdownItem: { type: Array as PropType<dropdownItem[]>, required: true },
    text: { type: String as PropType<string>, required: true },
    variant: { type:  String as PropType<'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark' | 'link'>, default: 'primary' },
    ariaLabel: { type: String as PropType<string>, default: undefined },
    autoClose: { type: [Boolean, String] as PropType<boolean | string>, default: true },
    boundary: { type: String as PropType<string>, default: 'clippingAncestors' },
    boundaryPadding: { type: [Number, String] as PropType<number | string>, default: undefined },
    disabled: { type: Boolean as PropType<boolean>, default: false },
    floatingMiddleware: { type: Array, default: undefined },
    icon: { type: Boolean as PropType<boolean>, default: false },
    id: { type: String as PropType<string>, default: undefined },
    initialAnimation: { type: Boolean as PropType<boolean>, default: false },
    isNav: { type: Boolean as PropType<boolean>, default: false },
    lazy: { type: Boolean as PropType<boolean>, default: false },
    menuClass: { type: [String , Array, Object] as PropType<string | object>, default: undefined },
    modelValue: { type: Boolean as PropType<boolean>, default: false },
    noAnimation: { type: Boolean as PropType<boolean>, default: false },
    noCaret: { type: Boolean as PropType<boolean>, default: false },
    noFade: { type: Boolean as PropType<boolean>, default: false },
    noFlip: { type: Boolean as PropType<boolean>, default: false },
    noShift: { type: Boolean as PropType<boolean>, default: false },
    noSize: { type: Boolean as PropType<boolean>, default: false },
    noWrapper: { type: Boolean as PropType<boolean>, default: false },
    offset: { type: [Number, String, Object] as PropType<number | string | object>, default: 0 },
    placement: { type: String as PropType<string>, default: 'bottom-start' },
    role: { type: String as PropType<string>, default: 'menu' },
    show: { type: Boolean as PropType<boolean>, default: false },
    size: { type: String as PropType<'sm' | 'md' | 'lg'>, default: 'md' },
    split: { type: Boolean as PropType<boolean>, default: false },
    splitButtonType: { type: String as PropType<string>, default: 'button' },
    splitClass: { type: [String, Array, Object], default: undefined },
    splitDisabled: { type: Boolean as PropType<boolean>, default: undefined },
    splitHref: { type: String as PropType<string>, default: undefined },
    splitTo: { type: [String, Object], default: undefined },
    splitVariant: { type: String as PropType<string>, default: undefined },
    strategy: { type: String as PropType<string>, default: 'absolute' },
    teleportDisabled: { type: Boolean as PropType<boolean>, default: false },
    teleportTo: { type: [String, Object], default: undefined },
    toggleClass: { type: [String, Array, Object], default: undefined },
    toggleText: { type: String as PropType<string>, default: 'Toggle dropdown' },
    transProps: { type: Object, default: undefined },
    unmountLazy: { type: Boolean as PropType<boolean>, default: false },
    visible: { type: Boolean as PropType<boolean>, default: false },
    wrapperClass: { type: [String, Array, Object], default: undefined }
}
