
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = (T & DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }>)


export const BootstrapContentAboutUs: typeof import("../components/bootstrap/content/aboutUs.vue")['default']
export const BootstrapContentHeaderContent: typeof import("../components/bootstrap/content/headerContent.vue")['default']
export const BootstrapCustomAccordion: typeof import("../components/bootstrap/customAccordion.vue")['default']
export const BootstrapCustomAlert: typeof import("../components/bootstrap/customAlert.vue")['default']
export const BootstrapCustomAvatar: typeof import("../components/bootstrap/customAvatar.vue")['default']
export const BootstrapCustomBadge: typeof import("../components/bootstrap/customBadge.vue")['default']
export const BootstrapCustomBreadcrumb: typeof import("../components/bootstrap/customBreadcrumb.vue")['default']
export const BootstrapCustomButton: typeof import("../components/bootstrap/customButton.vue")['default']
export const BootstrapCustomCard: typeof import("../components/bootstrap/customCard.vue")['default']
export const BootstrapCustomCheckbox: typeof import("../components/bootstrap/customCheckbox.vue")['default']
export const BootstrapCustomChooseFile: typeof import("../components/bootstrap/customChooseFile.vue")['default']
export const BootstrapCustomCollapse: typeof import("../components/bootstrap/customCollapse.vue")['default']
export const BootstrapCustomDropdown: typeof import("../components/bootstrap/customDropdown.vue")['default']
export const BootstrapCustomForm: typeof import("../components/bootstrap/customForm.vue")['default']
export const BootstrapCustomImage: typeof import("../components/bootstrap/customImage.vue")['default']
export const BootstrapCustomInput: typeof import("../components/bootstrap/customInput.vue")['default']
export const BootstrapCustomModal: typeof import("../components/bootstrap/customModal.vue")['default']
export const BootstrapCustomOffcanvas: typeof import("../components/bootstrap/customOffcanvas.vue")['default']
export const BootstrapCustomPlaceholder: typeof import("../components/bootstrap/customPlaceholder.vue")['default']
export const BootstrapCustomProgress: typeof import("../components/bootstrap/customProgress.vue")['default']
export const BootstrapCustomRadioButton: typeof import("../components/bootstrap/customRadioButton.vue")['default']
export const BootstrapCustomSearch: typeof import("../components/bootstrap/customSearch.vue")['default']
export const BootstrapCustomSelect: typeof import("../components/bootstrap/customSelect.vue")['default']
export const BootstrapCustomSpinner: typeof import("../components/bootstrap/customSpinner.vue")['default']
export const BootstrapCustomTable: typeof import("../components/bootstrap/customTable.vue")['default']
export const BootstrapCustomTabs: typeof import("../components/bootstrap/customTabs.vue")['default']
export const BootstrapCustomTooltip: typeof import("../components/bootstrap/customTooltip.vue")['default']
export const BootstrapLayoutFooterWebSite: typeof import("../components/bootstrap/layout/footerWebSite.vue")['default']
export const BootstrapLayoutHeaderWebSite: typeof import("../components/bootstrap/layout/headerWebSite.vue")['default']
export const BootstrapSectionsAdminPanelFormSection: typeof import("../components/bootstrap/sections/adminPanel/formSection.vue")['default']
export const BootstrapSectionsWebSiteFeaturesSection: typeof import("../components/bootstrap/sections/webSite/featuresSection.vue")['default']
export const BootstrapSectionsWebSiteHeroSection: typeof import("../components/bootstrap/sections/webSite/heroSection.vue")['default']
export const BootstrapSectionsWebSiteSplitHero: typeof import("../components/bootstrap/sections/webSite/splitHero.vue")['default']
export const BootstrapSlidersCustomCarousel: typeof import("../components/bootstrap/sliders/customCarousel.vue")['default']
export const SidbarProfile: typeof import("../components/sidbar/profile.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const BAccordion: typeof import("bootstrap-vue-next/components/BAccordion")['BAccordion']
export const BAccordionItem: typeof import("bootstrap-vue-next/components/BAccordion")['BAccordionItem']
export const BAlert: typeof import("bootstrap-vue-next/components/BAlert")['BAlert']
export const BApp: typeof import("bootstrap-vue-next/components/BApp")['BApp']
export const BAvatar: typeof import("bootstrap-vue-next/components/BAvatar")['BAvatar']
export const BAvatarGroup: typeof import("bootstrap-vue-next/components/BAvatar")['BAvatarGroup']
export const BBadge: typeof import("bootstrap-vue-next/components/BBadge")['BBadge']
export const BBreadcrumb: typeof import("bootstrap-vue-next/components/BBreadcrumb")['BBreadcrumb']
export const BBreadcrumbItem: typeof import("bootstrap-vue-next/components/BBreadcrumb")['BBreadcrumbItem']
export const BButton: typeof import("bootstrap-vue-next/components/BButton")['BButton']
export const BButtonGroup: typeof import("bootstrap-vue-next/components/BButton")['BButtonGroup']
export const BButtonToolbar: typeof import("bootstrap-vue-next/components/BButton")['BButtonToolbar']
export const BCloseButton: typeof import("bootstrap-vue-next/components/BButton")['BCloseButton']
export const BCard: typeof import("bootstrap-vue-next/components/BCard")['BCard']
export const BCardBody: typeof import("bootstrap-vue-next/components/BCard")['BCardBody']
export const BCardFooter: typeof import("bootstrap-vue-next/components/BCard")['BCardFooter']
export const BCardGroup: typeof import("bootstrap-vue-next/components/BCard")['BCardGroup']
export const BCardHeader: typeof import("bootstrap-vue-next/components/BCard")['BCardHeader']
export const BCardImg: typeof import("bootstrap-vue-next/components/BCard")['BCardImg']
export const BCardSubtitle: typeof import("bootstrap-vue-next/components/BCard")['BCardSubtitle']
export const BCardText: typeof import("bootstrap-vue-next/components/BCard")['BCardText']
export const BCardTitle: typeof import("bootstrap-vue-next/components/BCard")['BCardTitle']
export const BCarousel: typeof import("bootstrap-vue-next/components/BCarousel")['BCarousel']
export const BCarouselSlide: typeof import("bootstrap-vue-next/components/BCarousel")['BCarouselSlide']
export const BCol: typeof import("bootstrap-vue-next/components/BContainer")['BCol']
export const BCollapse: typeof import("bootstrap-vue-next/components/BCollapse")['BCollapse']
export const BContainer: typeof import("bootstrap-vue-next/components/BContainer")['BContainer']
export const BDropdown: typeof import("bootstrap-vue-next/components/BDropdown")['BDropdown']
export const BDropdownDivider: typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownDivider']
export const BDropdownForm: typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownForm']
export const BDropdownGroup: typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownGroup']
export const BDropdownHeader: typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownHeader']
export const BDropdownItem: typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownItem']
export const BDropdownItemButton: typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownItemButton']
export const BDropdownText: typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownText']
export const BForm: typeof import("bootstrap-vue-next/components/BForm")['BForm']
export const BFormCheckbox: typeof import("bootstrap-vue-next/components/BFormCheckbox")['BFormCheckbox']
export const BFormCheckboxGroup: typeof import("bootstrap-vue-next/components/BFormCheckbox")['BFormCheckboxGroup']
export const BFormDatalist: typeof import("bootstrap-vue-next/components/BForm")['BFormDatalist']
export const BFormFile: typeof import("bootstrap-vue-next/components/BFormFile")['BFormFile']
export const BFormFloatingLabel: typeof import("bootstrap-vue-next/components/BForm")['BFormFloatingLabel']
export const BFormGroup: typeof import("bootstrap-vue-next/components/BFormGroup")['BFormGroup']
export const BFormInput: typeof import("bootstrap-vue-next/components/BFormInput")['BFormInput']
export const BFormInvalidFeedback: typeof import("bootstrap-vue-next/components/BForm")['BFormInvalidFeedback']
export const BFormRadio: typeof import("bootstrap-vue-next/components/BFormRadio")['BFormRadio']
export const BFormRadioGroup: typeof import("bootstrap-vue-next/components/BFormRadio")['BFormRadioGroup']
export const BFormRating: typeof import("bootstrap-vue-next/components/BFormRating")['BFormRating']
export const BFormRow: typeof import("bootstrap-vue-next/components/BForm")['BFormRow']
export const BFormSelect: typeof import("bootstrap-vue-next/components/BFormSelect")['BFormSelect']
export const BFormSelectOption: typeof import("bootstrap-vue-next/components/BFormSelect")['BFormSelectOption']
export const BFormSelectOptionGroup: typeof import("bootstrap-vue-next/components/BFormSelect")['BFormSelectOptionGroup']
export const BFormSpinbutton: typeof import("bootstrap-vue-next/components/BFormSpinbutton")['BFormSpinbutton']
export const BFormTag: typeof import("bootstrap-vue-next/components/BFormTags")['BFormTag']
export const BFormTags: typeof import("bootstrap-vue-next/components/BFormTags")['BFormTags']
export const BFormText: typeof import("bootstrap-vue-next/components/BForm")['BFormText']
export const BFormTextarea: typeof import("bootstrap-vue-next/components/BFormTextarea")['BFormTextarea']
export const BFormValidFeedback: typeof import("bootstrap-vue-next/components/BForm")['BFormValidFeedback']
export const BImg: typeof import("bootstrap-vue-next/components/BImg")['BImg']
export const BInput: typeof import("bootstrap-vue-next/components/BFormInput")['BInput']
export const BInputGroup: typeof import("bootstrap-vue-next/components/BInputGroup")['BInputGroup']
export const BInputGroupText: typeof import("bootstrap-vue-next/components/BInputGroup")['BInputGroupText']
export const BListGroup: typeof import("bootstrap-vue-next/components/BListGroup")['BListGroup']
export const BListGroupItem: typeof import("bootstrap-vue-next/components/BListGroup")['BListGroupItem']
export const BModal: typeof import("bootstrap-vue-next/components/BModal")['BModal']
export const BModalOrchestrator: typeof import("bootstrap-vue-next/components/BModal")['BModalOrchestrator']
export const BNav: typeof import("bootstrap-vue-next/components/BNav")['BNav']
export const BNavForm: typeof import("bootstrap-vue-next/components/BNav")['BNavForm']
export const BNavItem: typeof import("bootstrap-vue-next/components/BNav")['BNavItem']
export const BNavItemDropdown: typeof import("bootstrap-vue-next/components/BNav")['BNavItemDropdown']
export const BNavText: typeof import("bootstrap-vue-next/components/BNav")['BNavText']
export const BNavbar: typeof import("bootstrap-vue-next/components/BNavbar")['BNavbar']
export const BNavbarBrand: typeof import("bootstrap-vue-next/components/BNavbar")['BNavbarBrand']
export const BNavbarNav: typeof import("bootstrap-vue-next/components/BNavbar")['BNavbarNav']
export const BNavbarToggle: typeof import("bootstrap-vue-next/components/BNavbar")['BNavbarToggle']
export const BOffcanvas: typeof import("bootstrap-vue-next/components/BOffcanvas")['BOffcanvas']
export const BOverlay: typeof import("bootstrap-vue-next/components/BOverlay")['BOverlay']
export const BOrchestrator: typeof import("bootstrap-vue-next/components/BApp")['BOrchestrator']
export const BPagination: typeof import("bootstrap-vue-next/components/BPagination")['BPagination']
export const BPlaceholder: typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholder']
export const BPlaceholderButton: typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholderButton']
export const BPlaceholderCard: typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholderCard']
export const BPlaceholderTable: typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholderTable']
export const BPlaceholderWrapper: typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholderWrapper']
export const BPopover: typeof import("bootstrap-vue-next/components/BPopover")['BPopover']
export const BProgress: typeof import("bootstrap-vue-next/components/BProgress")['BProgress']
export const BRow: typeof import("bootstrap-vue-next/components/BContainer")['BRow']
export const BSpinner: typeof import("bootstrap-vue-next/components/BSpinner")['BSpinner']
export const BTab: typeof import("bootstrap-vue-next/components/BTabs")['BTab']
export const BTabs: typeof import("bootstrap-vue-next/components/BTabs")['BTabs']
export const BToast: typeof import("bootstrap-vue-next/components/BToast")['BToast']
export const BToastOrchestrator: typeof import("bootstrap-vue-next/components/BToast")['BToastOrchestrator']
export const BTooltip: typeof import("bootstrap-vue-next/components/BTooltip")['BTooltip']
export const BLink: typeof import("bootstrap-vue-next/components/BLink")['BLink']
export const BProgressBar: typeof import("bootstrap-vue-next/components/BProgress")['BProgressBar']
export const BTableSimple: typeof import("bootstrap-vue-next/components/BTable")['BTableSimple']
export const BTableLite: typeof import("bootstrap-vue-next/components/BTable")['BTableLite']
export const BTable: typeof import("bootstrap-vue-next/components/BTable")['BTable']
export const BTbody: typeof import("bootstrap-vue-next/components/BTable")['BTbody']
export const BTd: typeof import("bootstrap-vue-next/components/BTable")['BTd']
export const BTh: typeof import("bootstrap-vue-next/components/BTable")['BTh']
export const BThead: typeof import("bootstrap-vue-next/components/BTable")['BThead']
export const BTfoot: typeof import("bootstrap-vue-next/components/BTable")['BTfoot']
export const BTr: typeof import("bootstrap-vue-next/components/BTable")['BTr']
export const BPopoverOrchestrator: typeof import("bootstrap-vue-next/components/BPopover")['BPopoverOrchestrator']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyBootstrapContentAboutUs: LazyComponent<typeof import("../components/bootstrap/content/aboutUs.vue")['default']>
export const LazyBootstrapContentHeaderContent: LazyComponent<typeof import("../components/bootstrap/content/headerContent.vue")['default']>
export const LazyBootstrapCustomAccordion: LazyComponent<typeof import("../components/bootstrap/customAccordion.vue")['default']>
export const LazyBootstrapCustomAlert: LazyComponent<typeof import("../components/bootstrap/customAlert.vue")['default']>
export const LazyBootstrapCustomAvatar: LazyComponent<typeof import("../components/bootstrap/customAvatar.vue")['default']>
export const LazyBootstrapCustomBadge: LazyComponent<typeof import("../components/bootstrap/customBadge.vue")['default']>
export const LazyBootstrapCustomBreadcrumb: LazyComponent<typeof import("../components/bootstrap/customBreadcrumb.vue")['default']>
export const LazyBootstrapCustomButton: LazyComponent<typeof import("../components/bootstrap/customButton.vue")['default']>
export const LazyBootstrapCustomCard: LazyComponent<typeof import("../components/bootstrap/customCard.vue")['default']>
export const LazyBootstrapCustomCheckbox: LazyComponent<typeof import("../components/bootstrap/customCheckbox.vue")['default']>
export const LazyBootstrapCustomChooseFile: LazyComponent<typeof import("../components/bootstrap/customChooseFile.vue")['default']>
export const LazyBootstrapCustomCollapse: LazyComponent<typeof import("../components/bootstrap/customCollapse.vue")['default']>
export const LazyBootstrapCustomDropdown: LazyComponent<typeof import("../components/bootstrap/customDropdown.vue")['default']>
export const LazyBootstrapCustomForm: LazyComponent<typeof import("../components/bootstrap/customForm.vue")['default']>
export const LazyBootstrapCustomImage: LazyComponent<typeof import("../components/bootstrap/customImage.vue")['default']>
export const LazyBootstrapCustomInput: LazyComponent<typeof import("../components/bootstrap/customInput.vue")['default']>
export const LazyBootstrapCustomModal: LazyComponent<typeof import("../components/bootstrap/customModal.vue")['default']>
export const LazyBootstrapCustomOffcanvas: LazyComponent<typeof import("../components/bootstrap/customOffcanvas.vue")['default']>
export const LazyBootstrapCustomPlaceholder: LazyComponent<typeof import("../components/bootstrap/customPlaceholder.vue")['default']>
export const LazyBootstrapCustomProgress: LazyComponent<typeof import("../components/bootstrap/customProgress.vue")['default']>
export const LazyBootstrapCustomRadioButton: LazyComponent<typeof import("../components/bootstrap/customRadioButton.vue")['default']>
export const LazyBootstrapCustomSearch: LazyComponent<typeof import("../components/bootstrap/customSearch.vue")['default']>
export const LazyBootstrapCustomSelect: LazyComponent<typeof import("../components/bootstrap/customSelect.vue")['default']>
export const LazyBootstrapCustomSpinner: LazyComponent<typeof import("../components/bootstrap/customSpinner.vue")['default']>
export const LazyBootstrapCustomTable: LazyComponent<typeof import("../components/bootstrap/customTable.vue")['default']>
export const LazyBootstrapCustomTabs: LazyComponent<typeof import("../components/bootstrap/customTabs.vue")['default']>
export const LazyBootstrapCustomTooltip: LazyComponent<typeof import("../components/bootstrap/customTooltip.vue")['default']>
export const LazyBootstrapLayoutFooterWebSite: LazyComponent<typeof import("../components/bootstrap/layout/footerWebSite.vue")['default']>
export const LazyBootstrapLayoutHeaderWebSite: LazyComponent<typeof import("../components/bootstrap/layout/headerWebSite.vue")['default']>
export const LazyBootstrapSectionsAdminPanelFormSection: LazyComponent<typeof import("../components/bootstrap/sections/adminPanel/formSection.vue")['default']>
export const LazyBootstrapSectionsWebSiteFeaturesSection: LazyComponent<typeof import("../components/bootstrap/sections/webSite/featuresSection.vue")['default']>
export const LazyBootstrapSectionsWebSiteHeroSection: LazyComponent<typeof import("../components/bootstrap/sections/webSite/heroSection.vue")['default']>
export const LazyBootstrapSectionsWebSiteSplitHero: LazyComponent<typeof import("../components/bootstrap/sections/webSite/splitHero.vue")['default']>
export const LazyBootstrapSlidersCustomCarousel: LazyComponent<typeof import("../components/bootstrap/sliders/customCarousel.vue")['default']>
export const LazySidbarProfile: LazyComponent<typeof import("../components/sidbar/profile.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyBAccordion: LazyComponent<typeof import("bootstrap-vue-next/components/BAccordion")['BAccordion']>
export const LazyBAccordionItem: LazyComponent<typeof import("bootstrap-vue-next/components/BAccordion")['BAccordionItem']>
export const LazyBAlert: LazyComponent<typeof import("bootstrap-vue-next/components/BAlert")['BAlert']>
export const LazyBApp: LazyComponent<typeof import("bootstrap-vue-next/components/BApp")['BApp']>
export const LazyBAvatar: LazyComponent<typeof import("bootstrap-vue-next/components/BAvatar")['BAvatar']>
export const LazyBAvatarGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BAvatar")['BAvatarGroup']>
export const LazyBBadge: LazyComponent<typeof import("bootstrap-vue-next/components/BBadge")['BBadge']>
export const LazyBBreadcrumb: LazyComponent<typeof import("bootstrap-vue-next/components/BBreadcrumb")['BBreadcrumb']>
export const LazyBBreadcrumbItem: LazyComponent<typeof import("bootstrap-vue-next/components/BBreadcrumb")['BBreadcrumbItem']>
export const LazyBButton: LazyComponent<typeof import("bootstrap-vue-next/components/BButton")['BButton']>
export const LazyBButtonGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BButton")['BButtonGroup']>
export const LazyBButtonToolbar: LazyComponent<typeof import("bootstrap-vue-next/components/BButton")['BButtonToolbar']>
export const LazyBCloseButton: LazyComponent<typeof import("bootstrap-vue-next/components/BButton")['BCloseButton']>
export const LazyBCard: LazyComponent<typeof import("bootstrap-vue-next/components/BCard")['BCard']>
export const LazyBCardBody: LazyComponent<typeof import("bootstrap-vue-next/components/BCard")['BCardBody']>
export const LazyBCardFooter: LazyComponent<typeof import("bootstrap-vue-next/components/BCard")['BCardFooter']>
export const LazyBCardGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BCard")['BCardGroup']>
export const LazyBCardHeader: LazyComponent<typeof import("bootstrap-vue-next/components/BCard")['BCardHeader']>
export const LazyBCardImg: LazyComponent<typeof import("bootstrap-vue-next/components/BCard")['BCardImg']>
export const LazyBCardSubtitle: LazyComponent<typeof import("bootstrap-vue-next/components/BCard")['BCardSubtitle']>
export const LazyBCardText: LazyComponent<typeof import("bootstrap-vue-next/components/BCard")['BCardText']>
export const LazyBCardTitle: LazyComponent<typeof import("bootstrap-vue-next/components/BCard")['BCardTitle']>
export const LazyBCarousel: LazyComponent<typeof import("bootstrap-vue-next/components/BCarousel")['BCarousel']>
export const LazyBCarouselSlide: LazyComponent<typeof import("bootstrap-vue-next/components/BCarousel")['BCarouselSlide']>
export const LazyBCol: LazyComponent<typeof import("bootstrap-vue-next/components/BContainer")['BCol']>
export const LazyBCollapse: LazyComponent<typeof import("bootstrap-vue-next/components/BCollapse")['BCollapse']>
export const LazyBContainer: LazyComponent<typeof import("bootstrap-vue-next/components/BContainer")['BContainer']>
export const LazyBDropdown: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown")['BDropdown']>
export const LazyBDropdownDivider: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownDivider']>
export const LazyBDropdownForm: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownForm']>
export const LazyBDropdownGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownGroup']>
export const LazyBDropdownHeader: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownHeader']>
export const LazyBDropdownItem: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownItem']>
export const LazyBDropdownItemButton: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownItemButton']>
export const LazyBDropdownText: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownText']>
export const LazyBForm: LazyComponent<typeof import("bootstrap-vue-next/components/BForm")['BForm']>
export const LazyBFormCheckbox: LazyComponent<typeof import("bootstrap-vue-next/components/BFormCheckbox")['BFormCheckbox']>
export const LazyBFormCheckboxGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BFormCheckbox")['BFormCheckboxGroup']>
export const LazyBFormDatalist: LazyComponent<typeof import("bootstrap-vue-next/components/BForm")['BFormDatalist']>
export const LazyBFormFile: LazyComponent<typeof import("bootstrap-vue-next/components/BFormFile")['BFormFile']>
export const LazyBFormFloatingLabel: LazyComponent<typeof import("bootstrap-vue-next/components/BForm")['BFormFloatingLabel']>
export const LazyBFormGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BFormGroup")['BFormGroup']>
export const LazyBFormInput: LazyComponent<typeof import("bootstrap-vue-next/components/BFormInput")['BFormInput']>
export const LazyBFormInvalidFeedback: LazyComponent<typeof import("bootstrap-vue-next/components/BForm")['BFormInvalidFeedback']>
export const LazyBFormRadio: LazyComponent<typeof import("bootstrap-vue-next/components/BFormRadio")['BFormRadio']>
export const LazyBFormRadioGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BFormRadio")['BFormRadioGroup']>
export const LazyBFormRating: LazyComponent<typeof import("bootstrap-vue-next/components/BFormRating")['BFormRating']>
export const LazyBFormRow: LazyComponent<typeof import("bootstrap-vue-next/components/BForm")['BFormRow']>
export const LazyBFormSelect: LazyComponent<typeof import("bootstrap-vue-next/components/BFormSelect")['BFormSelect']>
export const LazyBFormSelectOption: LazyComponent<typeof import("bootstrap-vue-next/components/BFormSelect")['BFormSelectOption']>
export const LazyBFormSelectOptionGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BFormSelect")['BFormSelectOptionGroup']>
export const LazyBFormSpinbutton: LazyComponent<typeof import("bootstrap-vue-next/components/BFormSpinbutton")['BFormSpinbutton']>
export const LazyBFormTag: LazyComponent<typeof import("bootstrap-vue-next/components/BFormTags")['BFormTag']>
export const LazyBFormTags: LazyComponent<typeof import("bootstrap-vue-next/components/BFormTags")['BFormTags']>
export const LazyBFormText: LazyComponent<typeof import("bootstrap-vue-next/components/BForm")['BFormText']>
export const LazyBFormTextarea: LazyComponent<typeof import("bootstrap-vue-next/components/BFormTextarea")['BFormTextarea']>
export const LazyBFormValidFeedback: LazyComponent<typeof import("bootstrap-vue-next/components/BForm")['BFormValidFeedback']>
export const LazyBImg: LazyComponent<typeof import("bootstrap-vue-next/components/BImg")['BImg']>
export const LazyBInput: LazyComponent<typeof import("bootstrap-vue-next/components/BFormInput")['BInput']>
export const LazyBInputGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BInputGroup")['BInputGroup']>
export const LazyBInputGroupText: LazyComponent<typeof import("bootstrap-vue-next/components/BInputGroup")['BInputGroupText']>
export const LazyBListGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BListGroup")['BListGroup']>
export const LazyBListGroupItem: LazyComponent<typeof import("bootstrap-vue-next/components/BListGroup")['BListGroupItem']>
export const LazyBModal: LazyComponent<typeof import("bootstrap-vue-next/components/BModal")['BModal']>
export const LazyBModalOrchestrator: LazyComponent<typeof import("bootstrap-vue-next/components/BModal")['BModalOrchestrator']>
export const LazyBNav: LazyComponent<typeof import("bootstrap-vue-next/components/BNav")['BNav']>
export const LazyBNavForm: LazyComponent<typeof import("bootstrap-vue-next/components/BNav")['BNavForm']>
export const LazyBNavItem: LazyComponent<typeof import("bootstrap-vue-next/components/BNav")['BNavItem']>
export const LazyBNavItemDropdown: LazyComponent<typeof import("bootstrap-vue-next/components/BNav")['BNavItemDropdown']>
export const LazyBNavText: LazyComponent<typeof import("bootstrap-vue-next/components/BNav")['BNavText']>
export const LazyBNavbar: LazyComponent<typeof import("bootstrap-vue-next/components/BNavbar")['BNavbar']>
export const LazyBNavbarBrand: LazyComponent<typeof import("bootstrap-vue-next/components/BNavbar")['BNavbarBrand']>
export const LazyBNavbarNav: LazyComponent<typeof import("bootstrap-vue-next/components/BNavbar")['BNavbarNav']>
export const LazyBNavbarToggle: LazyComponent<typeof import("bootstrap-vue-next/components/BNavbar")['BNavbarToggle']>
export const LazyBOffcanvas: LazyComponent<typeof import("bootstrap-vue-next/components/BOffcanvas")['BOffcanvas']>
export const LazyBOverlay: LazyComponent<typeof import("bootstrap-vue-next/components/BOverlay")['BOverlay']>
export const LazyBOrchestrator: LazyComponent<typeof import("bootstrap-vue-next/components/BApp")['BOrchestrator']>
export const LazyBPagination: LazyComponent<typeof import("bootstrap-vue-next/components/BPagination")['BPagination']>
export const LazyBPlaceholder: LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholder']>
export const LazyBPlaceholderButton: LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholderButton']>
export const LazyBPlaceholderCard: LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholderCard']>
export const LazyBPlaceholderTable: LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholderTable']>
export const LazyBPlaceholderWrapper: LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholderWrapper']>
export const LazyBPopover: LazyComponent<typeof import("bootstrap-vue-next/components/BPopover")['BPopover']>
export const LazyBProgress: LazyComponent<typeof import("bootstrap-vue-next/components/BProgress")['BProgress']>
export const LazyBRow: LazyComponent<typeof import("bootstrap-vue-next/components/BContainer")['BRow']>
export const LazyBSpinner: LazyComponent<typeof import("bootstrap-vue-next/components/BSpinner")['BSpinner']>
export const LazyBTab: LazyComponent<typeof import("bootstrap-vue-next/components/BTabs")['BTab']>
export const LazyBTabs: LazyComponent<typeof import("bootstrap-vue-next/components/BTabs")['BTabs']>
export const LazyBToast: LazyComponent<typeof import("bootstrap-vue-next/components/BToast")['BToast']>
export const LazyBToastOrchestrator: LazyComponent<typeof import("bootstrap-vue-next/components/BToast")['BToastOrchestrator']>
export const LazyBTooltip: LazyComponent<typeof import("bootstrap-vue-next/components/BTooltip")['BTooltip']>
export const LazyBLink: LazyComponent<typeof import("bootstrap-vue-next/components/BLink")['BLink']>
export const LazyBProgressBar: LazyComponent<typeof import("bootstrap-vue-next/components/BProgress")['BProgressBar']>
export const LazyBTableSimple: LazyComponent<typeof import("bootstrap-vue-next/components/BTable")['BTableSimple']>
export const LazyBTableLite: LazyComponent<typeof import("bootstrap-vue-next/components/BTable")['BTableLite']>
export const LazyBTable: LazyComponent<typeof import("bootstrap-vue-next/components/BTable")['BTable']>
export const LazyBTbody: LazyComponent<typeof import("bootstrap-vue-next/components/BTable")['BTbody']>
export const LazyBTd: LazyComponent<typeof import("bootstrap-vue-next/components/BTable")['BTd']>
export const LazyBTh: LazyComponent<typeof import("bootstrap-vue-next/components/BTable")['BTh']>
export const LazyBThead: LazyComponent<typeof import("bootstrap-vue-next/components/BTable")['BThead']>
export const LazyBTfoot: LazyComponent<typeof import("bootstrap-vue-next/components/BTable")['BTfoot']>
export const LazyBTr: LazyComponent<typeof import("bootstrap-vue-next/components/BTable")['BTr']>
export const LazyBPopoverOrchestrator: LazyComponent<typeof import("bootstrap-vue-next/components/BPopover")['BPopoverOrchestrator']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/nuxt-island")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@3.19.2_@parcel+watcher_7e51f20dbf562e6d1f316a0b26e2633b/node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
